import type { GameDefinition } from "./types";

export const games = [
  {
    slug: "snake",
    title: "Snake",
    genre: "Action",
    status: "playable",
    summary: "Guide the snake, chain apples, and beat your best run.",
    description: "A polished arcade classic rebuilt around clean turns and quick restarts.",
    accent: "green",
    preview: "snake",
    priority: 1,
    duration: "1-min rounds",
  },
  {
    id: "cipherword",
    slug: "cipher",
    title: "Cipher",
    genre: "Word",
    status: "playable",
    summary: "Find the hidden word with meaning scores, clues, and letters.",
    description:
      "A daily word puzzle where related guesses score by meaning and exact-length guesses reveal letter clues.",
    accent: "violet",
    preview: "cipherword",
    priority: 2,
    path: "/games/cipher",
    featured: true,
    favoriteReady: true,
    daily: true,
    modes: ["Daily", "Archive", "Unlimited", "Hard", "Zen"],
    duration: "2-4 min",
    tags: ["Daily", "Archive", "Semantic", "Word", "Logic", "Wordle", "Calendar", "Clue"],
  },
  {
    slug: "minesweeper",
    title: "Minesweeper",
    genre: "Puzzle",
    status: "coming-soon",
    summary: "Classic mine-clearing with clean counts and readable boards.",
    description: "Classic mine-clearing with clean counts and readable boards.",
    accent: "blue",
    preview: "minesweeper",
    priority: 3,
  },
  {
    slug: "pong",
    title: "Pong",
    genre: "Sports",
    status: "coming-soon",
    summary: "Fast paddle rallies with crisp ball movement.",
    description: "A planned lightweight arcade game with keyboard and touch-friendly controls.",
    accent: "slate",
    preview: "pong",
    priority: 4,
  },
  {
    slug: "tiles",
    title: "Tiles",
    genre: "Puzzle",
    status: "coming-soon",
    summary: "A compact falling-block puzzle built for quick sessions.",
    description: "A compact falling-block puzzle built for quick sessions.",
    accent: "violet",
    preview: "tiles",
    priority: 5,
  },
  {
    slug: "orbit",
    title: "Orbit",
    genre: "Adventure",
    status: "coming-soon",
    summary: "Time each tap to stay locked in orbit.",
    description: "Time each tap to stay locked in orbit.",
    accent: "teal",
    preview: "orbit",
    priority: 6,
  },
  {
    slug: "2048",
    title: "2048",
    genre: "Puzzle",
    status: "coming-soon",
    summary: "Slide numbers into larger, cleaner merges.",
    description: "A future implementation target once the hub has more playable games.",
    accent: "amber",
    preview: "number",
    priority: 7,
  },
  {
    slug: "dashline",
    title: "Dashline",
    genre: "Racing",
    status: "coming-soon",
    summary: "Clean routes, tight turns, and fast restarts.",
    description: "A quick racing challenge built for clean routes, tight turns, and fast restarts.",
    accent: "slate",
    preview: "dashline",
    priority: 8,
  },
  {
    slug: "sky-courier",
    title: "Sky Courier",
    genre: "Casual",
    status: "coming-soon",
    summary: "Tiny delivery routes through open sky lanes.",
    description: "Reserved for a calm flying loop with tiny deliveries and simple timing.",
    accent: "blue",
    preview: "sky-courier",
    priority: 9,
  },
  {
    slug: "family-stack",
    title: "Stack Party",
    genre: "Family",
    status: "coming-soon",
    summary: "Shared turns around balanced block stacks.",
    description: "A future family shelf game built around approachable goals and short rounds.",
    accent: "green",
    preview: "stack",
    priority: 10,
  },
  {
    slug: "sim-garden",
    title: "Garden Loop",
    genre: "Simulation",
    status: "coming-soon",
    summary: "Small garden systems with visible growth steps.",
    description: "A slower simulation concept for readable state changes and relaxed pacing.",
    accent: "teal",
    preview: "garden",
    priority: 11,
  },
  {
    slug: "strategy-path",
    title: "Route Tactics",
    genre: "Strategy",
    status: "coming-soon",
    summary: "Plan compact routes with visible tradeoffs.",
    description: "A turn-planning placeholder for a future strategy board.",
    accent: "amber",
    preview: "route",
    priority: 12,
  },
] satisfies GameDefinition[];

export type GameSlug = (typeof games)[number]["slug"];

export const playableGames = games.filter((game) => game.status === "playable");

export function getGameBySlug(slug: string) {
  return games.find((game) => game.slug === slug);
}

export function isGameSlug(slug: string): slug is GameSlug {
  return games.some((game) => game.slug === slug);
}
